//**********************************************************************
//    CopyRight  (c)  
//    File Name   :   CompCtrlDefine.C
//    Function    :   Store composite control define
//    Version     :   V3.2.0
//    Date        :   2022.02.16
///*********************************************************************
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
void IcResourceInit()
{
    
    /*<UserCodeStart>*//*<SinOne-Tag><37>*/
        SC_Init(); /***MCU init***/
        
    /*<UserCodeEnd>*//*<SinOne-Tag><37>*/
    
}

/*************************************.Generated by EasyCodeCube.************************************/
