//***************************************************************************************************
//    CopyRight  (c)  
//    File Name   :   CallBackFunction.c
//    Function    :   Write the logic you want to implement in the function body
//    Version     :   V3.0
//    Date        :   2022.07.14
//***************************************************************************************************
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
void Customer_BTM_Dispose()
{
/*<UserCodeStart>*//*<SinOne-Tag><825>*/
/*<UserCodeEnd>*//*<SinOne-Tag><825>*/
}
void Customer_IntoLowPowerMode_Init()
{
/*<UserCodeStart>*//*<SinOne-Tag><826>*/
/*<UserCodeEnd>*//*<SinOne-Tag><826>*/
}
void Customer_QuitLowPowerMode_Init()
{
/*<UserCodeStart>*//*<SinOne-Tag><827>*/
/*<UserCodeEnd>*//*<SinOne-Tag><827>*/
}
/*************************************.Generated by EasyCodeCube.************************************/
